// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU44ejop1PDH5tzqHMbPzMgkYo6XeDeRY',
    appId: '1:718298726796:web:eba27024d93e201e1a16a9',
    messagingSenderId: '718298726796',
    projectId: 'learn-2-earn-66fd2',
    authDomain: 'learn-2-earn-66fd2.firebaseapp.com',
    storageBucket: 'learn-2-earn-66fd2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGan-LFQlHaZ1ihI8x7dNFEfVxDdDQTbE',
    appId: '1:718298726796:android:5ab70760128ade021a16a9',
    messagingSenderId: '718298726796',
    projectId: 'learn-2-earn-66fd2',
    storageBucket: 'learn-2-earn-66fd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLOeKc4YOV9_lHrtI00YL8_BhkBIgWAcc',
    appId: '1:718298726796:ios:d3c01fc7f3d1a4a61a16a9',
    messagingSenderId: '718298726796',
    projectId: 'learn-2-earn-66fd2',
    storageBucket: 'learn-2-earn-66fd2.firebasestorage.app',
    iosBundleId: 'com.example.learn2earn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLOeKc4YOV9_lHrtI00YL8_BhkBIgWAcc',
    appId: '1:718298726796:ios:d3c01fc7f3d1a4a61a16a9',
    messagingSenderId: '718298726796',
    projectId: 'learn-2-earn-66fd2',
    storageBucket: 'learn-2-earn-66fd2.firebasestorage.app',
    iosBundleId: 'com.example.learn2earn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU44ejop1PDH5tzqHMbPzMgkYo6XeDeRY',
    appId: '1:718298726796:web:1e49a18e35e6fa341a16a9',
    messagingSenderId: '718298726796',
    projectId: 'learn-2-earn-66fd2',
    authDomain: 'learn-2-earn-66fd2.firebaseapp.com',
    storageBucket: 'learn-2-earn-66fd2.firebasestorage.app',
  );

}